
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{.Release.namespace}}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion : v1
kind : ConfigMap
metadata :
  name: backend-config
  namespace: {{.Release.namespace}}
data:
  SPRING_DATASOURCE_URL : jdbc:mysql://db-service:3306/exdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: tester

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{.Release.namespace}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: studnet-backend-{{ .Chart.Name }}
        image: {{.Values.image.repository }}/studnet-backend:{{ .Values.image.tag}}
        resources:
          limits:
            cpu: "0.2"
            memory: 500Mi
          requests:
            cpu: "0.1"
            memory: 250Mi
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-user-password
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: SPRING_DATASOURCE_USERNAME
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 5
        startupProbe:
          exec:
            command:
            - touch
            - /tmp/healthy
          failureThreshold: 30
          periodSeconds: 5