apiVersion: v1
kind: Secret
metadata: 
  name: db-secret
  namespace: {{.Release.namespace}}
type: Opaque
data:
  mysql-user-password:  dEBzdEByMkA=
  mysql-root-password:  cEBzc3dAcmRyQEB0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: {{.Release.namespace}}
data:
  username: "tester"
  db-name: "exdb"

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{.Release.namespace}}
spec:
  selector:
    app: mysql
  ports :
    - protocol : TCP
      port : 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: {{.Release.namespace}}
spec:
  serviceName: db-service
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-database
        image: mysql:9.1.0-oracle
        resources:
          limits:
            cpu: "0.2"
            memory: 700Mi
          requests:
            cpu: "0.1"
            memory: 500Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-configmap
                key: db-name
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-configmap
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-user-password
        ports:
          - containerPort: 3306
            name: db-port
        volumeMounts:
          - name: storagevol
            mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 5
        startupProbe:
          exec:
            command:
            - touch
            - /tmp/healthy
          failureThreshold: 30
          periodSeconds: 5

  volumeClaimTemplates:
  - metadata:
      name: storagevol
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

