apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name : db-pdb
  namespace: {{.Release.namespace}}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mysql

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name : backend-pdb
  namespace: {{.Release.namespace}}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name : frontend-pdb
  namespace: {{.Release.namespace}}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend