apiVersion: v1
kind: ResourceQuota
metadata: 
  name: resource-quota
  namespace: {{.Release.namespace}}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi